controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
home:
    path: /inicio
    controller: App\Controller\HomeController::index
    
animales:
    path: /animales/{nombre}/{apellidos}
    controller: App\Controller\HomeController::animales
    defaults: {nombre: 'GATO', apellidos: 'Y perros'}
    methods: [GET, PUT]
    requirements:
        nombre: '[a-zA-Z]+'
        apellidos: '[1-9]+'
        
redirigir:
    path: /redirigir
    controller: App\Controller\HomeController::redirigir
    
animal_index:
    path: /animal/index
    controller: App\Controller\AnimalController::index
    
animal_save:
    path: /animal/save
    controller: App\Controller\AnimalController::save
    
animal_detail:
    path: /animal/{id}
    controller: App\Controller\AnimalController::animal